openapi: 3.0.3
info:
  title: Student Performance ML Prediction API
  description: >-
    This API can be used to predict whether or not a student described by a set
    of input features is a high quality student (by CMU admissions criteria)
    with high probability.


    Uses a backend cached pretrained ML model trained on a set of student data.
  version: 1.0.0
servers:
  - url: https://127.0.0.5
tags:
  - name: predict
    description: Used to predict student quality
paths:
  /predict:
    get:
      tags:
        - predict
      summary: Returns prediction of student quality
      description: >-
        Returns a boolean of whether or not the student is likely to be
        considered high quality.
      parameters:
        - name: failures
          in: query
          description: number of past class failures (numeric value from n if 1<=n<3, else 4)
          required: true
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 4
        - name: absences
          in: query
          description: number of school absences (numerical value from 0 to 93)
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 93
        - name: G1
          in: query
          description: first period grade (numeric value from 0 to 20)
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 20
        - name: G2
          in: query
          description: second period grade (numeric value from 0 to 20)
          required: true
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 20
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Predict'
        '400':
          description: Malformed request
        '422':
          description: Query values do not satisfy accepted data ranges
components:
  schemas:
    Predict:
      type: object
      properties:
        high_quality:
          type: boolean
          example: true
